### ISSUE TITLE
Cannot use tempo silence feature from Python

### ISSUE THREAD

**Issue by MathieuSornay** [piem/aubio#21]
I'm trying to write an example/audiotrack clone using python bindings but I cannot use the silence threshold feature.

It seems that : 
* `aubio_tempo_set_silence()` sets a parameter that is never used.
* `aubio_silence_detection()` is not binded in Python

**Comment by piem** [comment]
Hi Mathieu,

thanks for the report. i will open a new bug for aubio_tempo.

best, Paul
