### ISSUE TITLE
Segmentation Fault with Tempo

### ISSUE THREAD

**Issue by tigerite** [piem/aubio#24]
Hi

I'm getting a segmentation fault with some audio files when using aubio's tempo function from Python.

The segmentation fault also occurs with the aubiotrack  command line application.

I've uploaded the audio file here:
http://expirebox.com/download/62baf44f6fc330cfc4df32f070839d62.html

I suspect it may have to do with the size or amount of silences in the track.

I'm using the aubio 0.4.1.

Thanks!

**Comment by piem** [comment]
Hi tigerite, I think this is fixed in the develop branch, can you check?

**Comment by piem** [comment]
sorry, I can't actually reproduce the bug. what platform are you on?

**Comment by tigerite** [comment]
I'm on Ubuntu 14.0.4.

Aubio 0.4.1 compiled from source.

**Comment by piem** [comment]
ok, found it, thanks!

**Comment by tigerite** [comment]
I saw that 0.4.2 release was available with the fixes. Tried it and no more segmentation fault.Thanks!
